version: '3.1'
services:
    zoo-navigator:
        image: elkozmon/zoonavigator:1.0.1
        hostname: zoonavigator
        ports:
            - 9000:9000
        environment:
            HTTP_PORT: 9000
    kafka_manager:
        image: hlebalbau/kafka-manager:stable
        ports:
            - "9001:9000"
        environment:
            ZK_HOSTS: "192.168.0.67:2181,192.168.0.67:2182,192.168.0.67:2183"
            APPLICATION_SECRET: "random-secret"
        command: -Dpidfile.path=/dev/null
    #xinfra_monitor:
    #    image: xinfra:0.0.1
    #    ports:
    #        - "8000:8000"
    #        - "8778:8778"

    