version: '3.1'
services:
    prometheus:
        image: prom/prometheus:v2.19.1
        container_name: prometheus
        ports:
        - 9090:9090
        volumes:
            - ./prometheus-config/prometheus.yml:/prometheus/prometheus.yml
            #- ./data/prometheus:/data
        command:
            - '--config.file=/prometheus/prometheus.yml'
            #- '--storage.tsdb.path=/data'
        deploy:
          resources:
            limits:
              cpus: '0.25'
              memory: 1000M
    grafana:
        image: grafana/grafana:7.0.3
        container_name: grafana
        ports:
        - 9091:3000
        volumes:
            - ./grafana-storage:/var/lib/grafana
        deploy:
          resources:
            limits:
              cpus: '0.25'
              memory: 500M
        depends_on:
            - prometheus
    xinfra_monitor:
      build: XinfraMonitor
      image: xinfra:0.0.1
      ports:
          - "8000:8000"
          - "8778:8778"
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: 500M