global:
    scrape_interval: 10s
    evaluation_interval: 10s
scrape_configs:
    - job_name: 'kafka'
      static_configs: 
        - targets:
            - 192.168.0.199:2001 # kafka 1
            - 192.168.0.199:2002 # kafka 2
            - 192.168.0.199:2003 # kafka 3
    - job_name: 'zookeeper'
      static_configs: 
        - targets:
            - 192.168.0.199:3001 # zookeeper 1
            - 192.168.0.199:3002 # zookeeper 2
            - 192.168.0.199:3003 # zoopeeker 3  
    - job_name: 'kafka-connect'
      static_configs: 
        - targets:
            - 192.168.0.199:4001 # kafka-connect 1
  